DATA PREPROCESSING

- You can not fit models to features that are categorical.
- You have to convert categorical features (string) to numerical(float, bool, int.)

In [1]:
# Normalization

from sklearn.preprocessing import MinMaxScaler, StandardScaler

For preprocessing libraries we use fit_transform while for machine learning models we use just fit

In [2]:
# Example data
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]

# Initialize the scaler
scaler = MinMaxScaler()

# Fit and transform the data
scaled_data = scaler.fit_transform(data)

print(scaled_data)

[[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [1.   1.  ]]


In [3]:
import pandas as pd

In [4]:
df =pd.DataFrame(data)
df

0   1
0 -1.0   2
1 -0.5   6
2  0.0  10
3  1.0  18

In [5]:
scaled_df = scaler.fit_transform(df)
scaled_df

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [6]:
data1 = {
    'Feature1': [1.0, 2.0, 3.0, 4.0, 5.0],
    'Feature2': [10.0, 20.0, 30.0, 40.0, 50.0],
    'Feature3': [100.0, 200.0, 300.0, 400.0, 500.0]}

df = pd.DataFrame(data1)

df

Feature1  Feature2  Feature3
0       1.0      10.0     100.0
1       2.0      20.0     200.0
2       3.0      30.0     300.0
3       4.0      40.0     400.0
4       5.0      50.0     500.0

In [7]:
#initiate StandardScaler
scaler = StandardScaler()

# fit and transform the data
scaled_df = scaler.fit_transform(df)
scaled_df

array([[-1.41421356, -1.41421356, -1.41421356],
       [-0.70710678, -0.70710678, -0.70710678],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.70710678,  0.70710678,  0.70710678],
       [ 1.41421356,  1.41421356,  1.41421356]])

In [8]:
scaler = MinMaxScaler()
scaled_df = scaler.fit_transform(df)
scaled_df

array([[0.  , 0.  , 0.  ],
       [0.25, 0.25, 0.25],
       [0.5 , 0.5 , 0.5 ],
       [0.75, 0.75, 0.75],
       [1.  , 1.  , 1.  ]])

In [9]:
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]

In [10]:
print(data)

[[-1, 2], [-0.5, 6], [0, 10], [1, 18]]


In [11]:
# data mean and standard deviation
import numpy as np
print('Data Mean: ' , np.mean(data))
print('Data Standard Deviation: ', np.std(data) )

Data Mean:  4.4375
Data Standard Deviation:  6.2120724198933805


In [12]:
# initiate and scale data using StandardScaler
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)
scaled_data

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [13]:
print('Data Mean: ' , np.mean(scaled_data))
print('Data Standard Deviation: ', np.std(scaled_data) )

Data Mean:  0.0
Data Standard Deviation:  1.0


DATA ENCODING

Different ways of enconding
1. pandas get dummies/ one hot encoder
2. label encoder
3. ordinal encoder

In [14]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder
# Example data
data = ['cat', 'dog', 'mouse', 'cat']
data


['cat', 'dog', 'mouse', 'cat']

In [15]:
# Initialize the encoder
encoder = LabelEncoder()

# Fit and transform the data
encoded_data = encoder.fit_transform(data)

print(encoded_data)

[0 1 2 0]


In [16]:
dicts = {'animals': ['cat', 'dog', 'mouse', 'cat', 'mouse', 'joseph', 'ann'],
        'cost': [100,200,300,100,300,800,500]}

df = pd.DataFrame(dicts)
df

animals  cost
0     cat   100
1     dog   200
2   mouse   300
3     cat   100
4   mouse   300
5  joseph   800
6     ann   500

In [17]:
# pandas get dummies method
pd.get_dummies(df)

cost  animals_ann  animals_cat  animals_dog  animals_joseph  animals_mouse
0   100        False         True        False           False          False
1   200        False        False         True           False          False
2   300        False        False        False           False           True
3   100        False         True        False           False          False
4   300        False        False        False           False           True
5   800        False        False        False            True          False
6   500         True        False        False           False          False

In [18]:

# Initialize the one hot encoder
encoder = OneHotEncoder(sparse_output=False)

# Fit and transform the data
encoded_data = encoder.fit_transform(df[['animals']])

encoded_data

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.]])

In [19]:
# Initialize the ordinal encoder
encoder = OrdinalEncoder()

# Fit and transform the data
encoded_data = encoder.fit_transform(df[['animals']])

encoded_data

array([[1.],
       [2.],
       [4.],
       [1.],
       [4.],
       [3.],
       [0.]])